# Generated by Django 3.0.8 on 2020-07-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200709_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(max_length=4),
        ),
    ]
