# Generated by Django 3.0.8 on 2020-07-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200709_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='items',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing'),
        ),
    ]
