# Generated by Django 3.0.8 on 2020-07-10 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.Category'),
            preserve_default=False,
        ),
    ]
