# Generated by Django 3.0.8 on 2020-07-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
