# Generated by Django 3.0.8 on 2020-07-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='item_category',
        ),
    ]
