# Generated by Django 3.0.8 on 2020-07-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200713_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='winner',
            new_name='current_winner',
        ),
        migrations.AddField(
            model_name='listing',
            name='running',
            field=models.BooleanField(default=True),
        ),
    ]
