# Generated by Django 3.0.8 on 2020-07-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20200713_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
    ]
